const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const main = fs.readFileSync(path.join(root, "main.js"), "utf8");
const styles = fs.readFileSync(path.join(root, "styles.css"), "utf8");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "pipeline", "models.json"), "utf8"));
const worker = fs.readFileSync(path.join(root, "pipeline", "worker.cjs"), "utf8");

assert.ok(main.includes('pdfAiMode: "direct"'), "source-file mode must be the default");
assert.ok(main.includes('stored?.pdfAiMode === "local" ? "local" : "direct"'), "missing saved mode must resolve to source-file mode");
assert.ok(main.includes('{ id: "local", label: "本地解析"'), "Composer mode menu must expose local processing");
assert.ok(main.includes('{ id: "direct", label: "源文件"'), "Composer must expose direct PDF mode");
assert.ok(main.includes("sendClaudianMessageWithPdf"), "PDF preparation must be part of the Composer send path");
assert.ok(main.includes("turnRequestOverride: request"), "Composer must separate visible text from injected PDF context");
assert.ok(main.includes("request.externalContextPaths"), "direct mode must attach the real PDF path to the agent turn");
assert.ok(main.includes("composerPdfFilePath"), "external PDF drops must resolve to a real file for direct mode");
assert.ok(main.includes("if (createdStrip) this.renderComposerPdfTray(tab)"), "focus discovery must not redraw a pressed PDF control");
assert.ok(main.includes("strip.hidden = !isVisible"), "the PDF toolbar must hide when no attachment is pending");
assert.ok(main.includes('addEventListener("pointerdown", (event) => event.stopPropagation())'), "PDF controls must isolate pointer events from the Composer wrapper");
assert.ok(main.includes("if (button.parentElement !== actions) actions.append(button)"), "focus discovery must not remount the pressed settings button");
assert.ok(main.includes("state.topControlsObserver = new MutationObserver"), "runtime navigation redraws must restore the settings button");
assert.ok(main.includes("queueLinkedPdfAttachments"), "document selections and regions must attach their source without blocking visible text");
assert.ok(main.includes("this.queueLinkedPdfAttachments(tab, list)"), "selected text must be inserted while full-document parsing continues in the background");
assert.ok(main.includes("buildInitialLocalPdfContext"), "local mode must build one initial document context");
assert.ok(main.includes("tryNativeLocalPdfPipeline"), "installed no-torch model packs must route through the native worker");
assert.ok(main.includes("installLocalPipelinePack"), "settings must provide a model-pack installer");
assert.ok(main.includes("downloadLocalPipelineFile"), "model downloads must use the verified resumable downloader");
assert.ok(main.includes("removeLocalPipelinePack"), "users must be able to remove the downloaded pack");
assert.ok(main.includes('process.versions.node'), "worker launcher must verify a real Node runtime instead of trusting an exit code");
assert.ok(main.includes('prepared.pdfMode === "direct"'), "the send path must honor automatic source-file fallback");
assert.ok(main.includes("localFallbackReason"), "automatic source-file fallback must remain visible to the user");
assert.ok(main.includes("queueComposerPdfAttachment"), "dropped documents must appear before local preparation finishes");
assert.ok(main.includes("startComposerPdfLocalPreparation"), "switching to local mode must immediately prepare existing attachments");
assert.ok(main.includes('const showProcessing = currentMode === "local" && Boolean(attachment.processing)'), "source-file mode must not keep showing background local progress");
assert.ok(main.includes('progressTrack.style.display = showProcessing ? "block" : "none"'), "document card progress must follow the selected mode");
assert.ok(main.includes('if (mode === "local" && attachment.processingError)'), "background local errors must not block source-file sends");
assert.ok(main.includes("hasComposerDirectContextBinding"), "linked source documents must track established model-session context");
assert.ok(main.includes("introduce the actual source document only once per model session"), "linked source documents must not be reintroduced on every turn");
assert.ok(main.includes("directContextPaths.push(path)"), "linked source paths must remain available without repeating document instructions");
assert.ok(main.includes("rememberComposerDirectContextBindings"), "successful source context admission must be persisted");
assert.ok(main.includes("hasComposerLocalContextBinding"), "linked local documents must track established model-session context");
assert.ok(main.includes("rememberComposerLocalContextBindings"), "successful local context admission must be persisted");
assert.ok(main.includes("后续消息不会再次注入或检索"), "local context must explicitly be admitted only once per model session");
assert.ok(!main.includes("localPdfSearchTerms"), "later local turns must not run prompt-based document retrieval");
assert.ok(main.includes("const introduceLocalContext = !prepared.workspaceLinked"), "linked local context must be skipped after its first admission");
assert.ok(main.includes("const seenDocumentCards = new Set()"), "historical repeated document cards must collapse to their first occurrence");
assert.ok(main.includes("invalidateComposerDirectContextBindings"), "failed provider sessions must rebuild source context on retry");
assert.ok(main.includes("state.directContextInflight.has(inflightKey)"), "queued turns must not duplicate a source context still being admitted");
assert.ok(main.includes('state.contextRow.className = "paper-composer-context-row paperlib-composer-context-row"'), "document cards must share the native Composer context tray");
assert.ok(!main.includes('modeGroup.className = "paperlib-composer-pdf-mode"'), "mode controls must not remain beside document cards");
assert.ok(main.includes('application/x-paperlib-pdf-selection'), "native document text drag must retain its source path and page");
assert.ok(main.includes("processingProgress"), "Composer attachments must retain per-document parsing progress");
assert.ok(main.includes("formatAIRemainingTime"), "Composer parsing progress must include an estimated remaining time");
assert.ok(main.includes('nodePath.join(outputPath, "cache.json")'), "local parsing metadata must be persisted next to each cached result");
assert.ok(main.includes("cacheHit"), "reused parsing results must be surfaced to the Composer UI");
assert.ok(main.includes("const alreadyOpen = Boolean(runtime.getView?.())"), "first Composer activation must not create a duplicate conversation tab");
assert.ok(!main.includes("openSmartComposer(true)"), "launch actions must focus the Composer instead of creating another conversation tab");
assert.ok(!main.includes("pdfjs-document-index"), "PDF.js text indexes must never act as a MinerU fallback");
assert.ok(!main.includes("getCachedPdfSessionForAI"), "legacy PDF.js extraction cache must stay removed");
assert.ok(!main.includes("class PaperLibraryAIView"), "standalone Paper AI view must be removed");
assert.ok(!main.includes('id: "open-paper-ai"'), "standalone Paper AI command must be removed");
assert.ok(main.includes('detachLeavesOfType("paper-library-ai-view")'), "upgrades must remove persisted Paper AI leaves");
assert.ok(!main.includes('aiApiKey: ""'), "Paper Library must not keep a second API credential path");
assert.ok(styles.includes(".paperlib-composer-mode-option.is-active"), "the compact settings menu must show the selected mode");
assert.ok(styles.includes(".paperlib-composer-pdf-chip"), "PDFs must be rendered as Composer attachment cards");
assert.ok(styles.includes(".paperlib-composer-pdf-progress"), "attachment cards must render local parsing progress");
assert.ok(styles.includes('.paperlib-composer-pdf-strip[hidden]'), "hidden PDF controls must not reserve Composer space");
assert.ok(styles.includes("background: transparent !important"), "mode buttons must not use Obsidian grey button surfaces");

assert.equal(manifest.policies.shipPyTorch, false);
assert.equal(manifest.policies.shipPaddlePython, false);
assert.equal(manifest.policies.allowPdfJsFallback, false);
assert.equal(manifest.policies.fallbackToSourceFile, true);
assert.equal(manifest.policies.quantized, false);
assert.equal(manifest.policies.weights, "fp32");
assert.deepEqual(manifest.runtimeOrder, ["layout", "formula", "ocr", "table", "markdown"]);
const names = new Set(manifest.models.map((model) => model.upstream));
["PP-DocLayoutV2", "ch_PP-OCRv6_small_det_infer", "ch_PP-OCRv6_small_rec_infer",
  "SLANet-plus", "UnetStructure", "PP-LCNet_table_cls", "PP-FormulaNet_plus-M"]
  .forEach((name) => assert.ok(names.has(name), `missing MinerU model contract: ${name}`));
assert.ok(![...names].some((name) => /DocLayout-YOLO/i.test(name)), "legacy layout model must not enter the MinerU pack");
assert.ok(fs.existsSync(path.join(root, "pipeline", "worker-protocol.md")), "native worker contract must be documented");
assert.ok(worker.includes("PaddleStructureService.createInstance"), "worker must initialize the document structure pipeline");
assert.ok(worker.includes('path.join(modelRoot, "layout/config.json")'), "worker must use the downloaded PP-DocLayoutV2 contract");
assert.ok(worker.includes("fast_tokenizer_file"), "formula recognition must read the nested tokenizer payload");
assert.ok(worker.includes('dictionary.push(" ")'), "OCR must append the configured space character");
assert.ok(worker.includes("[6, 8].includes"), "layout parsing must accept the downloaded model's extended rows");
assert.ok(worker.includes('process.argv.includes("--self-test")'), "installer must be able to validate the local worker before marking it ready");
assert.ok(worker.includes('layout: { enabled: true'), "worker must enable layout inference");
assert.ok(worker.includes('ocr: { enabled: true'), "worker must enable OCR inference");
assert.ok(worker.includes('table: { enabled: true'), "worker must enable table inference");
assert.ok(worker.includes('formula: { enabled: true'), "worker must enable formula inference");
assert.ok(worker.includes('markdown: { enabled: true'), "worker must compose Markdown output");

console.log("Paper Composer PDF dual-mode tests passed.");
